name: JavaScripts

# Run on push
on:
  push:
    # any branch
    branches:
      - '*'
      # If files matching these patterns have changed
    paths:
      - 'package.json'
      - 'admin/**'
      - readme.txt
      - .github/workflows/tests-js.yml

jobs:
  buildAndTest:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: yarn
      - name: Test
        run: yarn test --ci
